#!/bin/bash

echo "🔥 Firebase Complete Setup Instructions"
echo "======================================"
echo ""
echo "To fix the save functionality and enable all features, you need to configure"
echo "both Firestore and Storage security rules in Firebase Console."
echo ""
echo "📁 Files created:"
echo "- ./firestore.rules (for database)"
echo "- ./storage.rules (for file uploads)"
echo ""

echo "🗄️  STEP 1: Configure Firestore Database Rules"
echo "=============================================="
echo "1. Go to Firebase Console: https://console.firebase.google.com/"
echo "2. Select your project: 'the-name-nursery'"
echo "3. Go to 'Firestore Database'"
echo "4. Click on the 'Rules' tab"
echo "5. Replace the existing rules with the content from ./firestore.rules"
echo "6. Click 'Publish'"
echo ""
echo "Firestore rules content:"
echo "------------------------"
cat firestore.rules
echo ""

echo "📁 STEP 2: Configure Storage Rules"
echo "=================================="
echo "1. In the same Firebase Console"
echo "2. Go to 'Storage'"
echo "3. Click on the 'Rules' tab"
echo "4. Replace the existing rules with the content from ./storage.rules"
echo "5. Click 'Publish'"
echo ""
echo "Storage rules content:"
echo "----------------------"
cat storage.rules
echo ""

echo "✅ STEP 3: Verify Services are Enabled"
echo "======================================"
echo "Make sure these services are enabled in Firebase Console:"
echo "- Authentication (with Google & Email providers)"
echo "- Firestore Database (in production mode)"
echo "- Storage (default bucket)"
echo ""

echo "🧪 STEP 4: Test Everything"
echo "=========================="
echo "After applying rules, test your app:"
echo "1. Sign in to your app"
echo "2. Generate some names"
echo "3. Click the heart (🤍) to save a name"
echo "4. Upload a profile picture"
echo "5. Check your profile to see saved names and avatar"
echo ""
echo "🔧 Debug: If issues persist, open browser console and run:"
echo "testFirebaseConnection()"
echo ""
echo "🎉 All set! Your Firebase backend should now work perfectly!"
